#!/bin/bash
ret=0
if [ $# -eq 0 ]; then
    timeout 6 ./reaper/reaper -new -nosplash &>/dev/null # still evaluating
    tests="*.rks"
else
    tests=$@
fi

for test in *.rks; do
    echo "Running $test"
    expected=${test%.rks}.RPP
    out=out.RPP

    ./reaper/reaper -saveas $out -new -nosplash &>/dev/null &
    pid=$(echo $!)
    sleep 1
    xdotool search --onlyvisible --all reaper windowfocus &>/dev/null

    { <$test sed 's|"[^"]*$||' | tr ' ' '\n'
    } | while read cmd; do
        if [ "${cmd%${cmd#?}}" = "&" ]; then
            xdotool key "${cmd#?}"
        else
            xdotool type "$cmd"
        fi
        sleep .1
    done <$test

    xdotool type " ps"; sleep .5; kill $pid

    ./compare ${test%.rks}.RPP $out
    diff_ret=$(echo $?)
    echo "Test exit code $diff_ret"
    echo Stdout:
    cat stdout
    echo Stderr:
    cat stderr

    ret=$(( ret + diff_ret ))
    rm $out stdout stderr
done
exit $ret
